// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { vertexAiBlock } from ".";
import { auth } from "./auth";

export const vertexAiBlockSchema = parseBlockSchema(vertexAiBlock);
export const vertexAiCredentialsSchema = parseBlockCredentials(
  vertexAiBlock.id,
  auth.schema,
);
